apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: rabbitmq
spec:
  rules:
    - host: rabbitmq.minimix.com
      http:
        paths:
          - pathType: Prefix
            path: /
            # path: /rabbitmq(/|$)(.*)
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
